{% set python_min = "3.11" %}
{% set version = "0.0.6" %}
{% set name = "chemem" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SweeneyAaron/ChemEM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e60bffbaee427c5f46ca73be1016f6fc597bb272abd09a1e67bd566b7d7c1a91

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - chemem = ChemEM.chemem:main
    - chemem.test = ChemEM.chemem:test
    - chemem.protonate = ChemEM.chemem:protonate
    - chemem.alpha_mask = ChemEM.chemem:alpha_mask

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - openff-toolkit
  run:
    - python >={{ python_min }}
    - numpy <2.0.0
    - scipy 
    - dimorphite-dl >=2.0.1
    - spyrmsd >=0.8.0
    - rdkit
    - openff-toolkit
    - pdbfixer >=1.11
    - mrcfile >=1.5.0
    - pathos
    - biopython >=1.83
    - scikit-image

test:
  requires:
    - python
  imports:
    - ChemEM

about:
  home: https://github.com/SweeneyAaron/ChemEM
  summary: Software for fitting small molecules into Cryo-EM data.
  license: LicenseRef-ChemEM
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SweeneyAaron
